# default: true
phantomStun = true
# default: true
phantomSizeTweak = true
# default: true
phantomSpawnHealthTweak = true
# default: true
phantomSpawnTimingTweak = true
# default: true
phantomSpawnCountTweak = true
